---
- name: developer packages
  homebrew:
    state: present
    name:
      - aria2
      - awscli
      - cookiecutter
      - coreutils
      - dos2unix
      - fdupes
      - github/gh/gh # https://github.com/cli/cli
      - git-extras
      - gnupg
      - graphviz
      - hr
      - httpie
      - jq
      - lnav
      - md5deep
      - mmv
      - neofetch
      - nmap
      - p7zip
      - pandoc
      - pgcli
      - pv
      - readline
      - redis
      - ruby-build
      - thefuck

- name: find where asdf was installed
  command: "brew --prefix asdf"
  register: asdf_location
  changed_when: false

- debug: msg="{{ asdf_location.stdout }}"

- name: ensure asdf is in the $PATH
  blockinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    block: |
      export ASDF_DIR={{ asdf_location.stdout }}
      export PATH=~/.asdf/shims:$PATH

- name: add asdf plugins
  command: "asdf plugin-add {{ item }}"
  with_items:
    - golang
    - ruby
    - nodejs
    - python
  ignore_errors: true

- name: set global asdf versions
  blockinfile:
    path: "{{ ansible_env.HOME }}/.tool-versions"
    create: true
    block: |
      golang 1.12.5
      nodejs 10.16.0
      python 3.6.8
      ruby 2.6.3

- name: update asdf plugin versions
  command: asdf plugin-update --all

# https://github.com/asdf-vm/asdf-nodejs/issues/82
- name: update the release keys
  command: "{{ ansible_env.HOME }}/.asdf/plugins/nodejs/bin/import-release-team-keyring"

- name: install asdf versions
  command: asdf install
  args:
    chdir: "{{ ansible_env.HOME }}"

- name: python packages
  pip:
    name:
      - csvkit
      - haxor-news
    state: present
    executable: ~/.asdf/shims/pip3.6

- name: ruby packages
  gem:
    name: "{{ item }}"
    state: present
    executable: ~/.asdf/shims/gem
  with_items:
    - git-pulls
    - seeing_is_believing
    - bropages

- name: node packages
  npm:
    name: "{{ item }}"
    state: present
    global: true
    executable: ~/.asdf/shims/npm
  with_items:
    - surge

- name: asdf reshim
  command: asdf reshim