---
- name: check if oh-my-zsh is installed
  stat:
    path: "{{ ansible_env.HOME }}/.oh-my-zsh"
  register: zsh_stat_result

- name: install oh-my-zsh
  include_tasks:
    file: oh-my-zsh.yml
  when: zsh_stat_result.stat.exists == False

- name: install antigen
  git: repo=https://github.com/zsh-users/antigen.git dest={{ ansible_env.HOME }}/antigen recursive=yes

- name: symlinking dotfiles
  file: src="{{ item }}" dest="{{ lookup('env','HOME') }}/.{{ item | basename }}" state=link
  with_fileglob:
    - "./*"

- name: restore dotfile config via mackup
  command: mackup restore --force

  #- name: downloading dircolors theme
  #  git: repo=https://github.com/gibbling/dircolors.git dest={{ ansible_env.HOME }}/.dircolors recursive=yes

- name: creates mutt configuration directory
  file: state=directory recurse=yes path={{ item }}
  with_items:
    - "{{ ansible_env.HOME }}/.mutt/cache/headers"
    - "{{ ansible_env.HOME }}/.mutt/cache/bodies"

- name: downloading mutt solarized theme
  git: repo=https://github.com/altercation/mutt-colors-solarized.git dest={{ ansible_env.HOME }}/.mutt/theme recursive=yes

#
#- name: tapping homebrew cask fonts
#  homebrew_tap:
#    name: homebrew/homebrew-cask-fonts
#
#- name: installing fonts for use in shell / other places
#  homebrew_cask: name={{ item }} state=present
#  with_items:
#    - font-inconsolata-for-powerline
#    - font-powerline-symbols
#    - font-hack-nerd-font
#    - font-source-code-pro
