---
- name: downloading prezto repo
  git: repo=https://github.com/sorin-ionescu/prezto.git dest={{ ansible_env.HOME }}/.zprezto recursive=yes

- name: downloading dircolors theme
  git: repo=https://github.com/gibbling/dircolors.git dest={{ ansible_env.HOME }}/.dircolors recursive=yes

- name: restore configuration via mackup
  command: mackup restore --force

- name: symlinking dotfiles
  file: src="{{ item }}" dest="{{ lookup('env','HOME') }}/.{{ item | basename }}" state=link
  with_fileglob:
    - ./*

- name: setting prezto as the default shell
  command: chsh -s /bin/zsh
  when: ansible_env.SHELL.find('zsh') == -1
