---
- name: downloading prezto repo
  git: repo=https://github.com/sorin-ionescu/prezto.git dest={{ ansible_env.HOME }}/.zprezto recursive=yes

- name: downloading dircolors theme
  git: repo=https://github.com/gibbling/dircolors.git dest={{ ansible_env.HOME }}/.dircolors recursive=yes

- name: symlinking dotfiles
  file: src="{{ item }}" dest="{{ lookup('env','HOME') }}/.{{ item | basename }}" state=link
  with_fileglob:
    - ./*

- name: creates mutt configuration directory
  file: state=directory recurse=yes path={{ item }}
  with_items:
    - "{{ ansible_env.HOME }}/.mutt/cache/headers"
    - "{{ ansible_env.HOME }}/.mutt/cache/bodies"

- name: downloading mutt solarized theme
  git: repo=https://github.com/altercation/mutt-colors-solarized.git dest={{ ansible_env.HOME }}/.mutt/theme recursive=yes

- name: restore configuration via mackup
  command: mackup restore --force

- name: check for oh my fish installation
  shell: omf
  args:
    executable: /usr/local/bin/fish
  register: oh_my_fish
  ignore_errors: yes

- name: download oh my fish installation
  get_url:
    url: https://get.oh-my.fish
    dest: /tmp/omf.fish
  when: oh_my_fish.failed

- name: install oh my fish
  command: fish /tmp/omf.fish --noninteractive --yes
  when: oh_my_fish.failed

- name: install fisherman
  get_url:
    url: https://git.io/fisher
    dest: "{{ ansible_env.HOME }}/.config/fish/functions/fisher.fish"

- name: check if bobthefish theme installed
  shell: omf theme bobthefish
  args:
    executable: /usr/local/bin/fish
  register: bob_the_fish
  ignore_errors: yes

- name: install bobthefish theme
  shell: omf install bobthefish
  args:
    executable: /usr/local/bin/fish
  when: bob_the_fish.failed

- name: tapping homebrew cask fonts
  homebrew_tap:
    name: homebrew/homebrew-cask-fonts

- name: installing fonts for use in shell / other places
  homebrew_cask: name={{ item }} state=present
  with_items:
    - font-inconsolata-for-powerline
    - font-hack-nerd-font
    - font-source-code-pro
    
- name: set fish theme to bobthefish
  shell: omf theme bobthefish
  args:
    executable: /usr/local/bin/fish
  when: bob_the_fish.failed

- name: setting fish as the default shell
  command: chsh -s /usr/local/bin/fish
  when: ansible_env.SHELL.find('fish') == -1
