---

- name: add home bin dir for custom scripts
  file: path={{ ansible_env.HOME }}/bin state=directory

- name: update homebrew
  homebrew: update_homebrew=yes

- name: applications
  homebrew_cask: name={{ item }} state=present
  with_items:
    - alfred
    - 1password
    - dropbox
    - drop-to-gif
    - evernote
    - firefox
    - flux
    - google-chrome
    - handbrake
    - keybase
    - libreoffice
    - skype
    - slack
    - spectacle
    - spotify
    - torbrowser
    - vlc
    - uninstallpkg

- name: developer packages
  homebrew: name={{ item }} state=present
  with_items:
    - awscli
    - cookiecutter
    - cowsay
    - dash
    - elixir
    - emacs
    - fortune
    - git
    - git-extras
    - graphviz
    - heroku/brew/heroku
    - hub
    - imagemagick
    - mysql
    - neomutt
    - node
    - pgcli
    - redis
    - sqlite
    - w3m

- name: developer applications
  homebrew_cask: name={{ item }} state=present
  with_items:
    - dash
    - gitkraken
    - iterm2
    - postico
    - sequel-pro
    - sourcetree
    - sublime-text
    - vagrant-manager
    - visual-studio-code

- name: quicklook plugins
  homebrew_cask: name={{ item }} state=present
  with_items:
    - betterzipql
    - qlcolorcode
    - qlmarkdown
    - qlstephen
    - quicklook-json
    - slack

- name: system packages
  homebrew: name={{ item }} state=present
  with_items:
    #- moreutils
    - aria2
    - coreutils
    - ctags
    - colordiff
    - dos2unix
    - exa
    - fasd
    - fdupes
    - figlet
    - fpp
    - fzf
    - gnupg
    - hr
    - htop-osx
    - httpie
    - ispell
    - jq
    - lesspipe
    - lnav
    - mackup
    - md5deep
    - ncdu
    - neofetch
    - nmap
    - pandoc
    - p7zip
    - poppler # for lesspipe
    - progress
    - pv
    - qt
    - rbenv
    - readline
    - rename
    - ripgrep
    - ruby-build
    - sox
    - the_silver_searcher
    - tig
    - trash
    - tree
    - tldr
    - tmux
    - unrar
    - wget
    - zsh

- name: install spacemacs
  git:
    repo: https://github.com/syl20bnr/spacemacs
    dest: "{{ ansible_env.HOME }}/.emacs.d"

- name: install useful fzf key bindings and fuzzy completion
  shell: $(brew --prefix)/opt/fzf/install --key-bindings --completion --no-update-rc

# see https://superuser.com/questions/256232/how-can-i-get-qmake-on-mac-os-x
- name: link qt
  homebrew: name=qt state=linked

- name: python packages
  pip: name={{ item }} state=present
  with_items:
    - csvkit
    - haxor-news

- name: ruby packages
  gem: name={{ item }} state=present
  with_items:
    - git-pulls
    - seeing_is_believing
    - bropages

- name: node packages
  gem: name={{ item }} state=present
  with_items:
    - tldr

- name: create alfred configuration directory
  file:
    path: "{{ ansible_env.HOME }}/Library/Application Support/Alfred 3/Alfred.alfredpreferences/preferences/features/websearch"
    state: directory

- name: symlink alfred configuration
  file:
    src: "{{ role_path }}/files/alfred/prefs.plist"
    dest: "{{ ansible_env.HOME }}/Library/Application Support/Alfred 3/Alfred.alfredpreferences/preferences/features/websearch/prefs.plist"
    state: link
    force: yes

- name: create sublime text 3 configuration directory
  file: path="{{ ansible_env.HOME }}/Library/Application Support/Sublime Text 3/Installed Packages" state=directory

# See https://stackoverflow.com/questions/19529999/add-package-control-in-sublime-text-3-through-the-command-line
- name: install sublime package control
  tags: editor
  get_url:
    url: https://packagecontrol.io/Package%20Control.sublime-package
    dest: "{{ ansible_env.HOME }}/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package"
