---
- name: ensure we have an .ssh dir with the correct perms
  file: path={{ ansible_env.HOME }}/.ssh state=directory mode=700

- name: add home bin dir for custom scripts
  file: path={{ ansible_env.HOME }}/bin state=directory

- name: install spacemacs
  git:
    repo: https://github.com/syl20bnr/spacemacs
    dest: "{{ ansible_env.HOME }}/.emacs.d"

# - name: install useful fzf key bindings and fuzzy completion
#   shell: $(brew --prefix)/opt/fzf/install --key-bindings --completion --no-update-rc

- name: developer packages
  homebrew:
    state: present
    name:
      - awscli
      - cookiecutter
      - emacs
      - git
      - git-extras
      - graphviz
      - heroku/brew/heroku
      - hub
      - imagemagick
      - mysql
      - neomutt
      - pgcli
      - redis
      - ruby-build
      - sqlite
      - w3m

- name: system packages
  homebrew: 
    state: present
    name:
      #- moreutils
      - aria2
      - asdf
      - coreutils
      - ctags
      - colordiff
      - dmenu
      - dos2unix
      - exa
      - fasd
      - fdupes
      - figlet
      - fish
      - fortune
      - fpp
      - fzf
      - gnupg
      - hr
      - htop-osx
      - httpie
      - ispell
      - jq
      - lesspipe
      - lnav
      - md5deep
      - ncdu
      - neofetch
      - nmap
      - pandoc
      - p7zip
      - poppler # for lesspipe
      - progress
      - pv
      - qt
      - readline
      - rename
      - ripgrep
      - sox
      - the_silver_searcher
      - tig
      - trash
      - tree
      - tldr
      - tmux
      - unrar
      - wget
      - zsh

- name: add asdf plugins
  command: "asdf plugin-add {{ item }}" 
  with_items:
    - ruby
    - golang
    - nodejs
  ignore_errors: yes

- name: set global asdf versions
  blockinfile:
    path: "{{ ansible_env.HOME }}/.tool-versions"
    create: yes
    block: |
      ruby 2.6.3
      golang 1.12.5
      nodejs 10.16.0

- name: update asdf plugin versions
  command: asdf plugin-update --all

- name: install asdf versions
  command: asdf install

- name: asdf reshim
  command: asdf reshim

- name: python packages
  pip: name={{ item }} state=present
  with_items:
    - csvkit
    - haxor-news
    - mackup

- name: ruby packages
  gem: name={{ item }} state=present
  with_items:
    - git-pulls
    - seeing_is_believing
    - bropages

- name: node packages
  gem: name={{ item }} state=present
  with_items:
    - surge
    - tldr
