---

- name: update homebrew
  homebrew: update_homebrew=yes

- name: applications
  homebrew_cask: name={{ item }} state=present
  with_items:
    - 1password
    #- alfred
    - dash
    - dropbox
    - evernote
    - google-chrome
    - handbrake
    - moom
    - libreoffice
    - spotify
    - vlc

- name: developer packages
  homebrew: name={{ item }} state=present
  with_items:
    - git
    - hub
    - imagemagick
    - mysql
    - node
    - redis
    - sqlite

- name: developer applications
  homebrew_cask: name={{ item }} state=present
  with_items:
    - dash
    - gitx
    - iterm2 # need configuration
    - sequel-pro
    - sublime-text3 # need configuration

- name: work
  homebrew_cask: name={{ item }} state=present
  with_items:
    - slack
    - lastpass

- name: quicklook plugins
  homebrew_cask: name={{ item }} state=present
  with_items:
    - betterzipql
    - qlcolorcode
    - qlmarkdown
    - qlstephen
    - quicklook-json
    - slack

- name: system packages
  homebrew: name={{ item }} state=present
  with_items:
    - ctags
    - dos2unix
    - fasd
    - fdupes
    - figlet
    - gnupg
    - hr
    - htop-osx
    - md5deep
    - ncdu
    - ngrok
    - nmap
    - readline
    - rename
    - rbenv
    - ruby-build
    - the_silver_searcher
    - tree
    - unrar
    - wget
    - zsh

