---

- name: add home bin dir for custom scripts
  file: path={{ ansible_env.HOME }}/bin state=directory

- name: update homebrew
  homebrew: update_homebrew=yes

- name: applications
  homebrew_cask: name={{ item }} state=present
  with_items:
    #- alfred
    - 1password
    - dash
    - dropbox
    - evernote
    - flux
    - google-chrome
    - handbrake
    - libreoffice
    - moom
    - phoenix
    - skype
    - spotify
    - torbrowser
    - vlc
    - uninstallpkg

- name: developer packages
  homebrew: name={{ item }} state=present
  with_items:
    - awscli
    - cowsay
    - fortune
    - git
    - git-extras
    - gitsh
    - graphviz
    - heroku-toolbelt
    - hub
    - imagemagick
    - leiningen
    - maven
    - mysql
    - node
    - pgcli
    - redis
    - sqlite

- name: developer applications
  homebrew_cask: name={{ item }} state=present
  with_items:
    - dash
    - gitkraken
    #- iterm2 # need configuration
    - macdown
    - postico
    - sequel-pro
    - sourcetree
    - sublime-text # need configuration
    - vagrant-manager

- name: work
  homebrew_cask: name={{ item }} state=present
  with_items:
    - slack
    - lastpass

- name: quicklook plugins
  homebrew_cask: name={{ item }} state=present
  with_items:
    - betterzipql
    - qlcolorcode
    - qlmarkdown
    - qlstephen
    - quicklook-json
    - slack

- name: system packages
  homebrew: name={{ item }} state=present
  with_items:
    #- moreutils
    - aria2
    - ctags
    - dos2unix
    - fasd
    - fdupes
    - figlet
    - gnupg
    - hr
    - htop-osx
    - httpie
    - jq
    - md5deep
    - ncdu
    - ngrok
    - nmap
    - pandoc
    - progress
    - pv
    - rbenv
    - readline
    - rename
    - ruby-build
    - the_silver_searcher
    - tig
    - tree
    - tmux
    - unrar
    - wget
    - zsh

- name: python packages
  pip: name={{ item }} state=present
  with_items:
    - csvkit

