---
# gtk theme's directory
# For themes see https://www.gnome-look.org/browse/cat/135/ord/rating/
- name: add a themes directory for gtk theming
  file: path={{ ansible_env.HOME }}/.themes state=directory

# https://regolith-linux.org/
- name: add regolith repo
  apt_repository:
    repo: ppa:kgilmer/regolith-stable
    state: present
  become: true

# https://github.com/unix121/i3wm-themer
- name: linux applications
  package: name={{ item }} state=present
  become: true
  with_items:
    - arc-theme # https://github.com/horst3180/arc-theme
    - gnome-tweaks
    - gnome-shell-extensions
    - feh  # wallpaper management
    - nitrogen  # wallpaper management
    - ranger # visual file manager
    - regolith-desktop

- name: install dropbox
  apt:
    deb: https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2019.02.14_amd64.deb
  become: true

# - name: other applications
#   package: name={{ item }} state=present
#   become: true
#   with_items:
#     - adobe-source-code-pro-fonts
#     - nerd-fonts-complete
#     - neomutt
#     - polybar

